version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"   # Puerto web de Jenkins
      - "50000:50000" # Puerto para agentes remotos
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMmNkMmYyOWY0ODc2NjQ0MTY1MmRkMjU3ZjgzZTg5NmMiLCJ0IjoiNTBkNzc3YjYtMDEwYi00M2IzLThlNGYtNjhjMDMwOThkNzUxIiwicyI6Ik1UUTFORGhrT1RJdE9EUXdOeTAwTTJaaExXRTJOR010TTJJd1lUZ3hPR0l6TW1KbCJ9

volumes:
  jenkins_home:
    driver: local
