pipeline {
    agent any

    stages {
        stage('Restore') {
            steps {
                bat 'dotnet restore'
            }
        }
        stage('Build') {
            steps {
                bat 'dotnet build --no-restore'
            }
        }
        stage('Test') {
            steps {
                bat 'dotnet test --no-build --verbosity normal'
            }
        }
        stage('Publish') {
            steps {
                bat 'dotnet publish --configuration Release --output ./publish'
            }
        }
        stage('Deploy Simulation') {
            steps {
                echo 'Simulated deployment'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed (success or fail).'
        }
        failure {
            echo 'Something went wrong during the pipeline.'
        }
    }
}
