pipeline {
    agent any

    environment {
        DOTNET_VERSION = '8.0'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ldavidflorez/proyecto-jenkins.git'
            }
        }

        stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build --no-restore --configuration Release'
            }
        }

        stage('Test') {
            steps {
                sh 'dotnet test --no-build --configuration Release --logger trx'
            }
        }

        stage('Publish') {
            steps {
                sh 'dotnet publish --no-build --configuration Release -o ./publish'
            }
        }

        stage('Deploy Simulation') {
            steps {
                echo "Simulating deployment... Files are in ./publish"
            }
        }
    }

    post {
        always {
            echo "Pipeline completed (success or fail)."
        }
        success {
            echo "Build and tests succeeded!"
        }
        failure {
            echo "Something went wrong during the pipeline."
        }
    }
}
